version: "3.9"

services:
  api:
    build: ..
    container_name: omnichat-api
    command: uvicorn omnichat.app:app --host 0.0.0.0 --port 8000
    env_file: ../.env           # re-use the same file you already filled
    depends_on:
      - redis
    ports:
      - "8000:8000"             # http://localhost:8000

  redis:
    image: redis:7
    container_name: omnichat-redis
    restart: unless-stopped
    expose:
      - "6379"
